### ISSUE TITLE
FAFMIP stress experiments.

### ISSUE THREAD

**Issue by russfiedler** [mom-ocean/MOM5#289]
The FAFMIP experiment design states that the added wind stress shouldn't affect the turbulent mixing scheme. However, in MOM5, the friction velocity is computed in the various vertical mixing routines locally using Velocity%smf_bgrid which has the correction added unconditionally at the moment.

I've come up with the following solution and will submit it in a day or so:

 My approach is to calculate ustar in ocean_sbc.F90 and place it in the "Velocity" derived type and pass it to the various mixing schemes that way. I have a logical namelist variable that controls whether the extra flux correction is used when computing ustar. The default will be that the correction is used in order to reproduce existing result.

The code changes are simple for kpp_mom4p1, chen and GOTM but there's a bit of mucking about for the redundant mom4p0 form of the kpp scheme.

Any other idea as to how to implement this?

**Comment by aidanheerdegen** [comment]
I wouldn't bother back-porting to the redundant mom4p0 scheme. Can it just be made incompatible with the FAFMIP experiment in some way? If not it could be documented not to be used for FAFMIP.

**Comment by StephenGriffies** [comment]
Thanks again @russfiedler  for finding another hole in the FAFMIP setup.  

I agree with @aidanheerdegen that we should not worry about the kpp_mom4p0 scheme.  Just document that it is not compatible with FAFMIP.

**Comment by russfiedler** [comment]
Actually it wasn't too difficult to implement it. I've asked Fabio to test what I've come up with and I'll issue the pull request once things are tested. In the meantime the commit is here if you want to have a look

https://github.com/russfiedler/mom/tree/fafmip_stress

**Comment by StephenGriffies** [comment]
Nice code change @russfiedler .  This cleans the code and fixes the FAFMIP case.  Minor suggestions.

--"do_ustar_correct" is perhaps better "do_ustar_correction"  to be consistent with other options. 

--On the following comment in ocean_sbc.F90

  ! FAFMIP stess experiment says do not do this. Default is tTRUE.

I suggest it say something like the following more verbose text:  

  ! Compute ustar including the adjusted/correction stress field that has now been included in smf. 
  ! Note, however, that the FAFMIP stess experiment says we should NOT include the perturbed
  ! stress when computing ustar since we do not wish to affect the mixing schemes.  Hence, we 
  ! should set do_ustar_correction=.false. for FAFMIP in which case ustar just has contributions 
  ! from the unperturbed stress. 
  !
  ! The code default is do_ustar_correction = .true. as this reproduces earlier behavior.

**Comment by russfiedler** [comment]
Thanks @StephenGriffies for supplying the words!  I've added that to the namelist description section.

**Comment by fabiobdias** [comment]
Hi all,

just to give some updates about tests with the latest code: the sanity test reproduces the control results and also reproduces temp = redist_heat for the length of the simulation (1-month run). I will start soon to produce the final FAF-HEAT and FAF-STRESS runs (80-year long) and will inform about the results as it comes along. Many thanks @russfiedler, @rfarneti and @StephenGriffies!

**Comment by fabiobdias** [comment]
Hi all,

just to give some updates about tests with the latest code: the sanity test reproduces the control results and also reproduces temp = redist_heat for the length of the simulation (1-month run). I will start soon to produce the final FAF-HEAT and FAF-STRESS runs (80-year long) and will inform about the results as it comes along. Many thanks @russfiedler, @rfarneti and @StephenGriffies!

**Comment by aekiss** [comment]
@russfiedler is this issue now resolved?
