### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Blue-Taylor** [mom-ocean/MOM5#293]
Am new to modeling and I'm trying to compile MOM5 and I get the following error

_Make failed to create lib_ocean.a_

Any idea where to look for errors?

**Comment by sankibilli** [comment]
A log file of the error

[error-mom.txt](https://github.com/mom-ocean/MOM5/files/3335717/error-mom.txt)

**Comment by marshallward** [comment]
From the top of the file:
```
use netcdf
    1
Fatal Error: Can't open module file 'netcdf.mod' for reading at (1): No such file or directory
make: *** [dump_field.o] Error 1
make: *** Waiting for unfinished jobs....
```
You need to modify your build template to see your netCDF module file, usually in something like `$NETCDF/include`, but you may need to discuss it with your system admins.

**Comment by marshallward** [comment]
Some more info, in case it helps.  You are probably using this template:

https://github.com/mom-ocean/MOM5/blob/master/bin/mkmf.template.gfortran

which also reads this environment file:

https://github.com/mom-ocean/MOM5/blob/master/bin/environs.gfortran

Having said that, I notice that your `-I` include flags in your `gfortran` commands do not include the netCDF paths, which have been commented out of the template.

There is probably an expectation here that you have netCDF modules (something like `use module netcdf`) which will set the `CPATH` for you, so that you do not need the `-I` flag.  But if you're not using a module, then you'll need to include this somewhere.

But I wonder if this is a problem with the gfortran build template that should be addressed somehow.

**Comment by Blue-Taylor** [comment]
Thank you @marshallward 

I included the netCDF paths in -I include flags in gfortran commands and it worked out.
