### ISSUE TITLE
Various issues with uninitialised variables

### ISSUE THREAD

**Issue by russfiedler** [mom-ocean/MOM5#349]
Recently we have found several instances of uninitialised variables/arrays causing problems. Many of these have escaped detection due to compilers often setting these to zero/.FALSE. automatically.

I'll list the problems here as they are found and make some pull requests.

`src/mom5/ocean_param/neutral/ocean_nphysics_new.F90` need to set use_this_module to .FALSE.

`/src/shared/exchange/xgrid.F90` various clock ids need to be set to zero. If left with potentially negative defaults errors are reported.

`src/ice_sis/ice_model.F90` In case of no subcycling `uf0` and `vf0` still require setting to zero.

`src/fms/fms.F90` `num_nml_error_codes` and `nml_error_codes` not set nor required but still printed

**Comment by aekiss** [comment]
good catch @russfiedler - are there compiler options we could use to print warnings (or abort compilation) on uninitialised variables?

**Comment by russfiedler** [comment]
It's actually Ilia Bermous who has located these problems at runtime, many of which should be caught with even the simplest test cases if compiled with options like `-check init`, `-ftrapuv` `-finit=keyword` in ifort. Intel has also brought in some checking of arrays. gfortran's -Wuninitialised might do some static analysis and catch some potential cases.

**Comment by aekiss** [comment]
This sounds like something that should be included in the CI scripts that check PRs. First do compile-time tests and then do test runs which will terminate at runtime if uninitialised data is used.

Would it be good for production code to also terminate if uninitialised data is used? I'm not sure if there'd be a performance penalty.

This looks relevant:
https://www.intel.com/content/www/us/en/developer/articles/technical/detection-of-uninitialized-floating-point-variables-in-intel-fortran.html

**Comment by russfiedler** [comment]
No, production code should be run with the highest feasible optimisation so you don't want checks like these implemented.

**Comment by iliabermous** [comment]
Here is a list of Intel compiler options used to detect the problems described by Russ Fiedler

 -check -check noarg_temp_created -init=snan,arrays,huge

I would also recommend to use the latest Intel compiler versions at least 19.X (2019). As the last option "-init=huge" (development of this option was requested by myself in 2013) became available from release 18.0. But we did not use this compiler release due to some bugs in the compiler.

**Comment by aekiss** [comment]
Thanks @iliabermous, we are currently using ifort version 19.0.5.281, but the newest we have access to on NCI is 2021.4.0 - do you see much advantage in upgrading to that?

**Comment by iliabermous** [comment]
The 2021.4.0 version has just been installed on gadi. Obviously it has not been tested. However Intel support has informed me recently that several bugs which I have found earlier in the Intel compiler have been fixed with this release. Beiung busy I have not  checked this as the latest compiler was not available on the system last week. I  use 2020.3.304 release properly tested for UM.
